[package]

name = "scoped-pool"
version = "0.1.0"
authors = ["Jonathan Reem <jonathan.reem@gmail.com>"]
repository = "https://github.com/reem/rust-scoped-pool.git"
description = ""
readme = "README.md"
license = "MIT"

[dependencies]
variance = "0.1"
crossbeam = "0.2"

